version: "3"
services:

  mysql-5-6:
    image: mysql:5.6.50
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3309:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql

  mysql-5-7:
    image: 'memsql/cluster-in-a-box:centos-7.3.6-ae5d1857b8-3.2.5-1.11.0'
    restart: always
    environment:
      ROOT_PASSWORD: "prisma"
      LICENSE_KEY: $SINGLESTORE_LICENSE_KEY 
      START_AFTER_INIT: "true"
    ports:
      - "3306:3306"
    networks:
      - databases

  mysql-8-0:
    image: mysql:8.0.22
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3307:3306"
    networks:
      - databases
    tmpfs: /var/lib/mysql8

  mariadb-10-0:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3308:3306"
    networks:
      - databases
    tmpfs: /var/lib/mariadb
    
networks:
  databases:
