version: "3"
services:

  qe-test-base:
    image: prismagraphql/build:test
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "ci_test_binary"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
      LOG_LEVEL: "error"
    volumes:
      - .:/root/build
    working_dir: /root/build/
    networks:
      - databases

  test-db-postgres-13:
    image: timescale/timescaledb:2.1.0-pg13
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
      PGDATA: "/pgtmpfs13"
    ports:
      - "5435:5432"
    networks:
      - databases
    tmpfs: /pgtmpfs12


networks:
  databases:
