version: "3"
services:

  qe-test-base:
    image: prismagraphql/build:test
    environment:
      SERVER_ROOT: /root/build
      COMMIT_SHA: "ci_test_binary"
      RUST_BACKTRACE: "1"
      IS_BUILDKITE: "1"
      RUST_LOG_FORMAT: "devel"
      LOG_LEVEL: "error"
    volumes:
      - .:/root/build
    working_dir: /root/build/
    networks:
      - databases

  test-db-mysql-8-0:
  singlestore:
    image: 'memsql/cluster-in-a-box:centos-7.3.6-ae5d1857b8-3.2.5-1.11.0'
    restart: always
    environment:
      ROOT_PASSWORD: "prisma"
      LICENSE_KEY: $SINGLESTORE_LICENSE_KEY 
      START_AFTER_INIT: "true"
    ports:
      - "3307:3306"
    networks:
      - databases
    volumes:
      - /home/runner/work/prisma-engines/prisma-engines/memsql:/var/lib/memsql


networks:
  databases:
  telemetry:
