[package]
authors = []
edition = "2018"
name = "mongodb-query-connector"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bigdecimal = "0.2"
futures = "0.3"
itertools = "0.8"
mongodb = {git = "https://github.com/mongodb/mongo-rust-driver.git"}
rand = "0.7"
serde_json = {version = "1.0", features = ["float_roundtrip"]}
thiserror = "1.0"
tokio = "1.0"
tracing = "0.1.22"
tracing-futures = "0.2.4"
uuid = "0.8"

[dependencies.connector-interface]
package = "query-connector"
path = "../query-connector"

[dependencies.prisma-value]
features = ["sql-ext"]
path = "../../../libs/prisma-value"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.datamodel]
path = "../../../libs/datamodel/core"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.cuid]
git = "https://github.com/prisma/cuid-rust"

[dependencies.user-facing-errors]
features = ["sql"]
path = "../../../libs/user-facing-errors"
