name: Introspection Engine
on:
  push:

jobs:

  compile:
    name: "Compile Introspection Engine tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: introspection-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test --no-run
        working-directory: introspection-engine/introspection-engine-tests

  test:
    name: "Test Introspection Engine - ${{ matrix.database }}"
    
    strategy:
      fail-fast: false
      matrix:
        database: [mysql]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d
        env:
          SINGLESTORE_LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE_KEY }}
      
      - run: mysql -u root -pprisma -e "SHOW DATABASES;"
      - run: mysql -u root -pprisma -e "CREATE DATABASE mysql;"
      - run: mysql -u root -pprisma -e "SHOW DATABASES;"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: introspection-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test ${{ matrix.database }}
        working-directory: introspection-engine/introspection-engine-tests
        env:
          CLICOLOR_FORCE: 1
          RUST_BACKTRACE: 1
