name: Introspection Engine
on:
  push:

jobs:

  test:
    name: "Test Introspection Engine - singlestore"
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d
        env:
          SINGLESTORE_LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE_KEY }}
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - run: mysql -h 127.0.0.1 -P 3307 -u root -pprisma -e "CREATE DATABASE mysql;" --loose-default-auth=mysql_native_password
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: introspection-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test mysql_8
        working-directory: introspection-engine/introspection-engine-tests
        env:
          CLICOLOR_FORCE: 1
