name: Migration Engine
on:
  push:

jobs:

  test:
    name: "Test Migration Engine - ${{ matrix.database }}"
    
    strategy:
      fail-fast: false
      matrix:
        database: [mysql_8]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start databases"
        run: docker-compose up -d
        env:
          SINGLESTORE_LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE_KEY }}
          
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test ${{ matrix.database }}
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1
