name: Query Engine
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Test Query Engine - ${{ matrix.connector }}"

    strategy:
      fail-fast: false
      matrix:
        connector:
          - postgres9
          - postgres10
          - postgres11
          - postgres12
          - postgres13
          - pgbouncer
          - mysql
          - mysql_5_6
          - mysql8
          - mariadb
          - mssql2017
          - mssql2019
          - sqlite

    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
      CURRENT_CONNECTOR: ${{ matrix.connector }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start database"
        run: make dev-${{ matrix.connector }}

      - name: "Set connector"
        run: echo "${{ matrix.connector }}" > current_connector

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: query-engine-${{ runner.os }}-cargo

      - name: "Build Migration and Query Engine"
        run: cargo build --all-features --release --bin query-engine --bin migration-engine

      - name: Run tests
        working-directory: query-engine/connector-test-kit
        run: SERVER_ROOT="../../" sbt test
